services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - pg-network-hmk

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    networks:
      - pg-network-hmk

  hmk_taxi_ingest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgdatabase
    environment:
      PGUSER: root
      PGPASSWORD: root
      PGHOST: pgdatabase
      PGPORT: 5432
      PGDATABASE: ny_taxi
    networks:
      - pg-network-hmk
    command:
      - --pg-user=root
      - --pg-pass=root
      - --pg-host=pgdatabase
      - --pg-port=5432
      - --pg-db=ny_taxi
      - --target-table=green_taxi_data_2025_11
      - --year=2025
      - --month=11
      - --chunksize=100000


volumes:
  ny_taxi_postgres_data:
  pgadmin_data:

networks:
  pg-network-hmk:
