[project]
name = "bruin-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbc-driver-manager>=1.10.0",
    "duckdb[adbc]>=1.4.4",
    "pyarrow>=23.0.1",
]
